# A few of my favorite brews

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# tmux, requires `reattach-to-user-namespace`
install reattach-to-user-namespace
install tmux

# Version Control
install git
install mercurial

# Editor
install vim

# Utilities
install archey
install wget
install youtube-dl

# Cleanup any outdated formulas from the cellar
cleanup

# Ask the doctor how things are
doctor
