" .vimrc
" Maintained by: Mark Nichols
" mark@zanshin.net
" http;//zanshin.net
"

" Forget compatibility with vi. Who cares.
set nocompatible

" Initialize vundle
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
Bundle 'gmarik/vundle'

" My Bundles
"
" original repositories on github
Bundle 'altercation/vim-colors-solarized'
Bundle 'scrooloose/nerdtree'

" non github repositories
Bundle 'git://git.wincent.com/command-t.git'

" end of Vundle setup

" Enable filetypes
filetype on
filetype plugin on
filetype indent on
syntax on

" Write out old file when switching between files
set autowrite

" Saves file when Vim loses focus
au FocusLost * :wa

" Use a different map leader than \
" and reduce lag after typing leader key + command
:let mapleader = "-"
set timeoutlen=500

" Switch between buffers without saving
set hidden

" Set the color scheme
colorscheme Tomorrow-Night-Bright

" Set font type and size
set guifont=Menlo:h14

" Set tab stuff
set tabstop=2        " 2 spaces for a tab
set shiftwidth=2     " 2 spaces for autoindenting
set softtabstop=2    " when <BS>, pretend a tab is removed even if spaces
set expandtab        " expand tabs to spaces (overloadable by file type)

" Use relative line numbers
set relativenumber
"set number

" Editor and Layout stuff
set laststatus=2        " always show the status line
set cmdheight=2         " and use a two-line tall status line
set showcmd             " show the command
set showmode            " and show the current mode
set termencoding=utf-8  " we like utf-8
set encoding=utf-8
set autoindent          " turns it on
set smartindent         " does the right thing (mostly) in programs
set linespace=3         " prefer a slight higher line height
set wrap                " use line wrapping
set textwidth=79        " at column 79
set formatoptions=qrn1
set ruler               " display current cursor position
set list                " show invisible characters
set listchars=tab:▸\ ,eol:¬,extends:❯,precedes:❮
set showmatch           " show matching brackets

" Map escape to jj -- much faster to reach and type
imap jj <esc>

" Searching
set incsearch           " use incremental search
set hlsearch            " highlight search results
set ignorecase          " ignore case when searching
set smartcase           " ignore case if search string is all lower case, case-sensitve otherwise

" Enable code folding
set foldenable

" Hide mouse when typing
set mousehide

" Open a vertical split and switch to it (-v)
nnoremap <leader>v <C-w>v<C-w>l

" Open a horizontal split and switch to it (-h)
nnoremap <leader>h <C-w>s<C-w>j

" Split windows below the current window
set splitbelow

" vimrc shortcuts
" open vimrc in new tab for editing
nmap <leader>ev :tabedit $MYVIMRC<cr>

" automatically source .vimrc when it is saved (from vimcasts.org #24)
if has("autocmd")
  autocmd! bufwritepost .vimrc source $MYVIMRC
endif

" Command line completion
"set wildmode                 " navigate <left> & <right> through completion lists
"set wildmode=list:longest    " allows expansion of items

" --------------------------------------------------------
" control whitespace preferences based on filetype
" --------------------------------------------------------
if has("autocmd")
  " enable file type detection
  filetype on

  " syntax of these languages is fussy over tabs Vs spaces
  autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
  autocmd Filetype yaml setlocal ts=2 sts=2 sw=2 expandtab

  " treat .rss files as XML
  autocmd BufNewFile,BufRead *.rss,*.atom setfiletype xml
  
  " markdown files
  autocmd BufNewFile,BufRead *.md,*.mkd,*.markdown setfiletype markdown
  autocmd BufNewFile,BufRead *.md,*.mkd,*.markdown set spell spelllang=en_us

  " non ruby files related to Ruby
  autocmd BufNewFile,BufRead Gemfile,Gemfile.lock,Guardfile setfiletype ruby
  autocmd BufNewFile,BufRead Rakefile setfiletype rake
  autocmd BufNewFile,BufRead Rakefile set syntax=ruby
  autocmd BufNewFile,BufRead *.rake setfiletype rake
  autocmd BufNEwFile,BufRead *.rake set syntax=ruby

  " Python files
  let NERDTreeIgnore = ['\.pyc$', '\~$', '\.rbc$']
  autocmd BufNewFile,BufRead *.py set ts=2 sts=2 sw=2 expandtab

endif

" ----------------------------------------------------------
" Stuff for Bundles
" ----------------------------------------------------------
" NERDTree
nmap <leader>nt :NERDTreeToggle <CR>

" show hidden files in NERDTree
let NERDTreeShowHidden=1

" ----------------------------------------------------------
"  finis 
" ----------------------------------------------------------

