#!/bin/bash

# --------------------------------------------------------------------
# exports
#
# This file defines all the exports
# --------------------------------------------------------------------

# Silence macOS warning about zsh
export BASH_SILENCE_DEPRECATION_WARNING=1

# export EDITOR, PAGER, and LESS
export VISUAL=nvim
export EDITOR="$VISUAL"
export PAGER=less
export LESS="-M -n -q -i -r"

# Force Firefox to use Wayland protocol and not XWayland
export MOZ_ENABLE_WAYLAND=1

# Setup for Go
export GOPATH=$HOME/code/golib:$HOME/code/go
export GOPRIVATE="github.com/zanshin"

# mutt GPG tty setting
export GPG_TTY=$(tty)

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";
export LC_CTYPE="en_US.UTF-8";

# Export settings for Wildfly reboot scripts
export CHEFTEST="/Users/mhn/code/chef/zomedev"
export CHEFPROD="/Users/mhn/code/chef/zome"
export CHEF_BASEDIR="/Users/mhn/code/chef"

# Export CARGO_HOME and RUSTUP_HOME for Rust
export CARGO_HOME="${HOME}/.cargo/bin/bin"
export RUSTUP_HOME="${HOME}/.rustup"

# OpenJDK
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home"

# Configure how history works
HISTCONTROL=ignoredups:ignorespace                # ignore dups and commands beginning with a space
HISTSIZE=5000000                                  # size of the run-time history list
HISTFILESIZE=$HISTSIZE                            # size of the history file cf. also shopt -s histappend
HISTIGNORE=ls:ll:la:l:cd:pwd:exit:mc:su:df:clear  # do not put these in history file
#HISTFILE=~/.bash_history-`hostname`               # track history by host
HISTTIMEFORMAT="%y/%m/%d %T "

# Force history to update each time command prompt is displayed
PROMPT_COMMAND='history -a'

# export settings
export HISTCONTROL HISTFILESIZE HISTSIZE HISTIGNORE HISTTIMEFORMAT

# more colors
export LS_COLORS='no=00:fi=00:di=01;34:ow=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

# --------------------------------------------------------------------
# Color man pages:
# --------------------------------------------------------------------
# export LESS_TERMCAP_mb=$'\E[01;31m'      # begin blinking
# export LESS_TERMCAP_md=$'\E[01;31m'      # begin bold
# export LESS_TERMCAP_me=$'\E[0m'          # end mode
# export LESS_TERMCAP_se=$'\E[0m'          # end standout-mode
# export LESS_TERMCAP_so=$'\E[01;44;33m'   # begin standout-mode - info box
# export LESS_TERMCAP_ue=$'\E[0m'          # end underline
# export LESS_TERMCAP_us=$'\E[01;32m'      # begin underline

