#!/bin/bash

# --------------------------------------------------------------------
# exports
#
# This file defines all the exports
# --------------------------------------------------------------------

# XDG_CONFIG_HOME, XDG_DATA_HOME, and XDG_CACHE_HOME are not usually set for
# macOS
if [[ "$myos" == "Darwin" ]]; then
    export XDG_CONFIG_HOME="$HOME/.config"
    export XDG_CACHE_HOME="$HOME/.cache"
    export XDG_DATA_HOME="$HOME/.local/share"
fi

# Silence macOS warning about zsh
export BASH_SILENCE_DEPRECATION_WARNING=1

# export EDITOR, PAGER, and LESS
export VISUAL=nvim
export EDITOR="$VISUAL"
export PAGER=less
# export LESS="-M -n -q -i -r"
export LESS="-FRq"

# Force Firefox to use Wayland protocol and not XWayland
export MOZ_ENABLE_WAYLAND=1

# Setup fo Jujutsu
export JJ_CONFIG=$XDG_CONFIG_HOME/jj

# Setup for Go
export GOPATH=$HOME/code/golib:$HOME/code/go
export GOPRIVATE="github.com/zanshin"

# Set CC for Raspberry Pi & Go
if [[ -e /proc ]]; then
  if [[ $(grep -e Raspberry /proc/cpuinfo) ]]; then
    export CC=/usr/bin/arm-linux-gnueabi-gcc
  fi
fi


# mutt GPG tty setting
export GPG_TTY=$(tty)

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";
export LC_CTYPE="en_US.UTF-8";

# Export CARGO_HOME and RUSTUP_HOME for Rust
export CARGO_HOME="${HOME}/.cargo"
export RUSTUP_HOME="${HOME}/.rustup"

# Export for nvm
# export NVM_DIR="$HOME/.nvm"
#   [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
#   [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
# export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}"  ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
# [ -s "$NVM_DIR/nvm.sh"  ] && \. "$NVM_DIR/nvm.sh"

# OpenJDK
# export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home"
export JAVA_HOME="$(brew --prefix openjdk 2>/dev/null)"

# Export DOCKER_CONFIG to move .docker to ~/.config/docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME"/docker-machine

# Configure how history works
HISTCONTROL=ignoredups:ignorespace                        # ignore dups and commands beginning with a space
HISTSIZE=5000000                                          # size of the run-time history list
HISTFILESIZE=$HISTSIZE                                    # size of the history file cf. also shopt -s histappend
HISTIGNORE=ls:ll:la:l:cd:pwd:exit:mc:su:df:clear:history  # do not put these in history file
#HISTFILE=~/.bash_history-`hostname`                      # track history by host
HISTTIMEFORMAT="%y/%m/%d %T "

# Force history to update each time command prompt is displayed
PROMPT_COMMAND='history -a'

# export settings
export HISTCONTROL HISTFILESIZE HISTSIZE HISTIGNORE HISTTIMEFORMAT

# more colors
export LS_COLORS='st=91:tw=91:no=00:fi=00:di=01;34:ow=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

# Use Neovim for man pages
export MANPAGER='nvim +Man!'

# Anthropic Environment with Ollama
export ANTHROPIC_AUTH_TOKEN=ollama
export ANTHROPIC_API_KEY=""
export ANTHROPIC_BASE_URL="http://localhost:11434"

# --------------------------------------------------------------------
# Color man pages:
# --------------------------------------------------------------------
# export LESS_TERMCAP_mb=$'\E[01;31m'      # begin blinking
# export LESS_TERMCAP_md=$'\E[01;31m'      # begin bold
# export LESS_TERMCAP_me=$'\E[0m'          # end mode
# export LESS_TERMCAP_se=$'\E[0m'          # end standout-mode
# export LESS_TERMCAP_so=$'\E[01;44;33m'   # begin standout-mode - info box
# export LESS_TERMCAP_ue=$'\E[0m'          # end underline
# export LESS_TERMCAP_us=$'\E[01;32m'      # begin underline

# -----------------
# Sourcegraph
# -----------------
# export PGPORT=5432
# export PGHOST=localhost
# export PGUSER=sourcegraph
# export PGPASSWORD=sourcegraph
# export PGDATABASE=sourcegraph
# export PGSSLMODE=disable

# Set Colors for use elsewhere
# Reset
Color_Off='\e[0m'       # Text Reset

# Regular Colors
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White

# Bold
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White

# Underline
UBlack='\e[4;30m'       # Black
URed='\e[4;31m'         # Red
UGreen='\e[4;32m'       # Green
UYellow='\e[4;33m'      # Yellow
UBlue='\e[4;34m'        # Blue
UPurple='\e[4;35m'      # Purple
UCyan='\e[4;36m'        # Cyan
UWhite='\e[4;37m'       # White

# Background
On_Black='\e[40m'       # Black
On_Red='\e[41m'         # Red
On_Green='\e[42m'       # Green
On_Yellow='\e[43m'      # Yellow
On_Blue='\e[44m'        # Blue
On_Purple='\e[45m'      # Purple
On_Cyan='\e[46m'        # Cyan
On_White='\e[47m'       # White

# High Intensity
IBlack='\e[0;90m'       # Black
IRed='\e[0;91m'         # Red
IGreen='\e[0;92m'       # Green
IYellow='\e[0;93m'      # Yellow
IBlue='\e[0;94m'        # Blue
IPurple='\e[0;95m'      # Purple
ICyan='\e[0;96m'        # Cyan
IWhite='\e[0;97m'       # White

# Bold High Intensity
BIBlack='\e[1;90m'      # Black
BIRed='\e[1;91m'        # Red
BIGreen='\e[1;92m'      # Green
BIYellow='\e[1;93m'     # Yellow
BIBlue='\e[1;94m'       # Blue
BIPurple='\e[1;95m'     # Purple
BICyan='\e[1;96m'       # Cyan
BIWhite='\e[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\e[0;100m'   # Black
On_IRed='\e[0;101m'     # Red
On_IGreen='\e[0;102m'   # Green
On_IYellow='\e[0;103m'  # Yellow
On_IBlue='\e[0;104m'    # Blue
On_IPurple='\e[0;105m'  # Purple
On_ICyan='\e[0;106m'    # Cyan
On_IWhite='\e[0;107m'   # White
