#!/bin/bash

# Usage:
#   bartermapp [arg1] [arg2]
#      arg1: terminal program to run
#      arg2: number of times do apply additional
#            x offset defined by xinterval

# Dependencies:
#   tdrop


xoffset=175
xinterval=60
yoffset=52
width=600
height=600
terminal=termite


x=$(expr $xoffset + $xinterval \* $2 - $xinterval)

tdrop -ma -w $width -h $height -x $x -y 52 -n $2 -f "-e $1" $terminal
